// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("Answer")]
    public partial class Answer
    {
        public Answer()
        {
            AnswerVotes = new HashSet<AnswerVote>();
            SubAnswers = new HashSet<SubAnswer>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid QuestionId { get; set; }
        public string Content { get; set; }
        public Guid? AuthorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PubDate { get; set; }
        public bool? Confirm { get; set; }
        public bool? MostConfirm { get; set; }

        [ForeignKey("AuthorId")]
        [InverseProperty("Answers")]
        public virtual User Author { get; set; }

        [ForeignKey("QuestionId")]
        [InverseProperty("Answers")]
        public virtual Question Questions { get; set; }

        [InverseProperty("Answer")]
        public virtual ICollection<AnswerVote> AnswerVotes { get; set; }
        [InverseProperty("PreAnswer")]
        public virtual ICollection<SubAnswer> SubAnswers { get; set; }

    }
}