// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("AnswerVote")]
    public partial class AnswerVote
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? AnswerId { get; set; }
        public Guid? UserId { get; set; }
        public Guid? QuestionId { get; set; }

        [ForeignKey("AnswerId")]
        [InverseProperty("AnswerVotes")]
        public virtual Answer Answer { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("AnswerVotes")]
        public virtual User User { get; set; }
    }
}