// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("CourseComment")]
    public partial class CourseComment
    {
        public CourseComment()
        {
            CourseSubComments = new HashSet<CourseSubComment>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public Guid? CourseId { get; set; }
        [StringLength(2000)]
        public string Content { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("CourseComments")]
        public virtual Course Course { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("CourseComments")]
        public virtual User User { get; set; }
        [InverseProperty("PreComment")]
        public virtual ICollection<CourseSubComment> CourseSubComments { get; set; }
    }
}