// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("CourseSave")]
    public partial class CourseSave
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public Guid? CourseId { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("CourseSaves")]
        public virtual Course Course { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("CourseSaves")]
        public virtual User User { get; set; }
    }
}