// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("Document")]
    public partial class Document
    {
        public Document()
        {
            DocumentSaves = new HashSet<DocumentSave>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SubId { get; set; }
        public bool IsDeleted { get; set; } = false;
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Guid? UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }
        public long ViewNumber { get; set; }
        public int DownloadNumber { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Documents")]
        public virtual User User { get; set; }
        [InverseProperty("Document")]
        public virtual ICollection<DocumentSave> DocumentSaves { get; set; }
    }
}