// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("PostSave")]
    public partial class PostSave
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(255)]
        public string PostId { get; set; }
        public Guid? UserId { get; set; }

        [ForeignKey("PostId")]
        [InverseProperty("PostSaves")]
        public virtual Post Post { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("PostSaves")]
        public virtual User User { get; set; }
    }
}