// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("QuestionTag")]
    public partial class QuestionTag
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? TagId { get; set; }

        [ForeignKey("Id")]
        [InverseProperty("QuestionTag")]
        public virtual Question IdNavigation { get; set; }
        [ForeignKey("TagId")]
        [InverseProperty("QuestionTags")]
        public virtual Tag Tag { get; set; }
    }
}