// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("Quiz")]
    public partial class Quiz
    {
        [Key]
        public Guid Id { get; set; }
        public string Question { get; set; }
        public string RightAnswer { get; set; }

        [ForeignKey("Id")]
        [InverseProperty("Quiz")]
        public virtual Exercise IdNavigation { get; set; }
    }
}