// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using VNH.Domain.Entities;

namespace VNH.Domain
{
    [Table("Quiz")]
    public partial class Quiz
    {
        [Key]
        public Guid Id { get; set; }

        [StringLength(500)]
        public string Content { get; set; }
        

        public Guid MultipleChoiceId { get; set; } =Guid.Empty;

        [InverseProperty("Quiz")]
        public virtual ICollection<QuizAnswer> QuizAnswers { get; set; }

        [ForeignKey("MultipleChoiceId")]
        [InverseProperty("Quiz")]
        public virtual MultipleChoice MultipleChoice { get; set; }

    }
}