// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.Domain
{
    [Table("TopicDetail")]
    public partial class TopicDetail
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? TopicId { get; set; }
        public Guid? TagId { get; set; }

        [ForeignKey("TagId")]
        [InverseProperty("TopicDetails")]
        public virtual Tag Tag { get; set; }
        [ForeignKey("TopicId")]
        [InverseProperty("TopicDetails")]
        public virtual Topic Topic { get; set; }
    }
}