// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.DataAccessLayer.Models
{
    [Table("Course")]
    public partial class Course
    {
        public Course()
        {
            CourseComments = new HashSet<CourseComment>();
            CourseRatings = new HashSet<CourseRating>();
            CourseSaves = new HashSet<CourseSave>();
            Lessons = new HashSet<Lesson>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string CourseName { get; set; }
        public string Description { get; set; }
        public Guid? UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Courses")]
        public virtual User User { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CourseComment> CourseComments { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CourseRating> CourseRatings { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CourseSave> CourseSaves { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}