// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.DataAccessLayer.Models
{
    [Table("DocumentSave")]
    public partial class DocumentSave
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public Guid? DocumentId { get; set; }

        [ForeignKey("DocumentId")]
        [InverseProperty("DocumentSaves")]
        public virtual Document Document { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("DocumentSaves")]
        public virtual User User { get; set; }
    }
}