// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.DataAccessLayer.Models
{
    [Table("Search")]
    public partial class Search
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        [StringLength(500)]
        public string Content { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Searches")]
        public virtual User User { get; set; }
    }
}