// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.DataAccessLayer.Models
{
    [Table("SubAnswer")]
    public partial class SubAnswer
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? PreAnswerId { get; set; }
        public string Content { get; set; }
        public Guid? AuthorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PubDate { get; set; }

        [ForeignKey("AuthorId")]
        [InverseProperty("SubAnswers")]
        public virtual User Author { get; set; }
        [ForeignKey("PreAnswerId")]
        [InverseProperty("SubAnswers")]
        public virtual Answer PreAnswer { get; set; }
    }
}