// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VNH.DataAccessLayer.Models
{
    [Table("Topic")]
    public partial class Topic
    {
        public Topic()
        {
            Posts = new HashSet<Post>();
            TopicDetails = new HashSet<TopicDetail>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }
        public Guid? AuthorId { get; set; }

        [ForeignKey("AuthorId")]
        [InverseProperty("Topics")]
        public virtual User Author { get; set; }
        [InverseProperty("Topic")]
        public virtual ICollection<Post> Posts { get; set; }
        [InverseProperty("Topic")]
        public virtual ICollection<TopicDetail> TopicDetails { get; set; }
    }
}